# Generated by Django 4.1.2 on 2022-10-28 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='docker_image',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('command', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Image',
            },
        ),
        migrations.CreateModel(
            name='Enviroment_Vars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('value', models.CharField(db_index=True, max_length=200)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.docker_image')),
            ],
            options={
                'db_table': 'Enviroment_Vars',
            },
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Status', models.CharField(choices=[('R', 'Running'), ('F', 'Finished')], default='F', max_length=1)),
                ('images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play.docker_image')),
            ],
            options={
                'db_table': 'Container',
            },
        ),
    ]
